# Generated by Django 6.0.2 on 2026-03-12 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barber_accounts', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtime',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_times', to='branches.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='workingtime',
            unique_together={('barber', 'branch', 'date')},
        ),
    ]
