# Generated by Django 6.0.4 on 2026-04-16 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barber_accounts', '0001_initial'),
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbers', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barberportfolioimage',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='barber_accounts.barberprofile'),
        ),
        migrations.AddField(
            model_name='barberportfolio',
            name='barber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='barber_accounts.barberprofile'),
        ),
        migrations.AddField(
            model_name='barberteammember',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='barber_accounts.barberprofile'),
        ),
        migrations.AddField(
            model_name='workingtime',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_times', to='barber_accounts.barberprofile'),
        ),
        migrations.AddField(
            model_name='workingtime',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_times', to='branches.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='workingtime',
            unique_together={('barber', 'branch', 'date')},
        ),
    ]
