# Generated by Django 6.0.4 on 2026-05-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='app_type',
            field=models.CharField(choices=[('customer', 'Customer App'), ('barber', 'Barber App')], default='customer', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersession',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
