# Generated by Django 6.0.4 on 2026-05-25 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HairTryOnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='hair_tryon/originals/')),
                ('haircut_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='hair_tryon/references/')),
                ('generated_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('pending', 'جاري المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل التوليد')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
