# Generated by Django 6.0.2 on 2026-03-15 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_accounts', '0002_initial'),
        ('booking', '0001_initial'),
        ('branches', '0001_initial'),
        ('customers_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='customers_accounts.customerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('barber', 'date', 'time')},
        ),
    ]
