# Generated by Django 6.0.4 on 2026-05-13 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('login', 'Login'), ('barber_advance_booking', 'Barber Advance Booking'), ('barber_home_booking', 'Barber Home Booking'), ('user_advance_booking', 'User Advance Booking'), ('user_home_booking', 'User Home Booking'), ('profile_updated', 'Profile Updated'), ('new_review', 'New Review'), ('general', 'General')], default='general', max_length=50)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('booking', 'Booking'), ('profile', 'Profile'), ('review', 'Review'), ('general', 'General')], default='general', max_length=30)),
                ('receiver_type', models.CharField(choices=[('customer', 'Customer'), ('barber', 'Barber'), ('admin', 'Admin')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('screen', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
