# Generated by Django 6.0.4 on 2026-05-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver_type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('barber', 'Barber'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
