# Generated by Django 6.0.4 on 2026-05-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_fcmdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='app_type',
            field=models.CharField(choices=[('customer', 'Customer App'), ('barber', 'Barber App')], default='customer', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
